# Generated by Django 3.2.7 on 2021-11-28 18:25

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='documents/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('maxmarks', models.PositiveIntegerField()),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('end_time', models.TimeField()),
                ('is_deadline_not_over', models.BooleanField(default=True, max_length=10)),
                ('marksfile', models.FileField(blank=True, null=True, upload_to='csvfile/')),
                ('weightage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='createdcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Length has to be 5', regex='^\\w{5}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='undertakingcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='submit_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='submissions/')),
                ('status', models.CharField(default='Not Evaluated', max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('obtainedmarks', models.IntegerField(default=0, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='float_moodle.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='moderatorrelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Length has to be 5', regex='^\\w{5}$')])),
                ('power', models.CharField(choices=[('1', 'one'), ('2', 'two')], max_length=3)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='float_moodle.createdcourses')),
            ],
        ),
        migrations.CreateModel(
            name='moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=5)),
                ('tacode', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='float_moodle.createdcourses'),
        ),
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('announcement', models.TextField(max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='float_moodle.createdcourses')),
            ],
        ),
    ]
